### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by mehulsatardekar**
Added Landing Page for Quiz app

Live Preview : https://deploy-preview-8--quizgrad.netlify.app/views/homepage

### CODE REVIEW

**Review by j24m — APPROVED** [review]
Wow, both code and UI are good, really good work :)

**Review by Sahil25061999 — APPROVED** [review]
code looks good, UI is beautiful. Just a suggestion for landing page, I am assuming it is just going to have start learning section, so you can disable the overflow section.

**Comment by mehulsatardekar** [comment]
@Sahil25061999 did all the changes

**Review by eakansh125 — COMMENTED** [review]
Suggestions but not mandates (Can be done later) 

1. Commented code can be removed
2. section home-banner is empty, that can be removed for now.

**Comment by AagmanSuri** [comment]
code looks neat and clean

**Pull request merged**
